name: OpenWrt RaspberryPi 4B

on:
  push:
    tags:
      - 'v*'
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  TZ: America/Toronto

jobs:
  OpenWrt-RaspberryPi: 
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Space cleanup
        run: |
          sudo -E apt-get update -y
          sudo -E apt-get full-upgrade -y
          sudo -E apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
            git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev \
            libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
            libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 \
            python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
            uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt-get clean
          sudo timedatectl set-timezone "$TZ"
      
      - name: Clone OpenWrt
        run: |
          git clone $REPO_URL openWrt

      - name: Update feeds
        run: |
          cd openWrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
        
      - name: Use .config from repository
        run: |
          cd openWrt
          rm -f ./.config*
          cp $GITHUB_WORKSPACE/.config .config
          make defconfig
    
      - name: Make download
        run: |
          cd openWrt
          make download -j8
          make V=s -j8
          cd bin/targets/bcm27xx/bcm2711 && ls -n
      
      - name: Upload release
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path');

            const { repo: { owner, repo }, sha } = context;
            console.log({ owner, repo, sha });

            const release = await github.repos.createRelease({
              owner, repo,
              draft: true,
              target_commitish: sha,
              tag_name: process.env.GITHUB_REF,
            });

            for (let file of await fs.readdirSync('./openWrt/bin/targets/bcm27xx/bcm2711')) {
              const filePath = `./openWrt/bin/targets/bcm27xx/bcm2711/${file}`

              if (/\.gz$/.test(file)) {
                await github.repos.uploadReleaseAsset({
                  repo,
                  owner, 
                  name: file,
                  release_id: release.data.id,
                  data: await fs.readFileSync(filePath)
                }); 
              }
            }
